Max length temporary name
xataio/pgroll pull request #275
Opened 2024-02-05 10:22 UTC by 9bany

Apply max length validation for temporary name
fixes: https://github.com/xataio/pgroll/issues/64

2024-02-09 15:14 UTC, andrew-farries commented on pkg/migrations/op_set_fk.go
> +	}
I don't think it makes sense to check the names of the triggers. The trigger functions are internal to `pgroll` and their names won't mean anything to the users starting the migration.

I would remove all the checks for trigger name length and just check the names of the user-defined parts of migrations like column and constraint names.

2024-03-01 08:43 UTC, SferaDev commented
@andrew-farries Updated with main and applied the changes to make CI checks pass

2024-03-05 12:07 UTC, andrew-farries requested changes

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/errors.go
> +	return fmt.Sprintf("max length of %q is %d", e.Name, e.Max)
```suggestion
	return fmt.Sprintf("length of %q (%d) exceeds maximum length of %d", e.Name, len(e.Name), e.Max)
```

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/name.go
> +}
Get rid of `validateName` and use the exported `ValidateName` everywhere.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/op_change_type.go
> +
I don't think it makes sense to check the length of the column name on the operation here as it must already exist in the database. The check can be removed.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/op_drop_column.go
> +	}
I don't think it makes sense to check the length of the column name on the operation here as it must already exist in the database. The check can be removed.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/op_drop_constraint.go
> +
I don't think it makes sense to check the length of the column name on the operation here as it must already exist in the database. The check can be removed.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/op_drop_not_null.go
> +
I don't think it makes sense to check the length of the column name on the operation here as it must already exist in the database. The check can be removed.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/op_set_check.go
> +
I don't think it makes sense to check the length of the column name on the operation here as it must already exist in the database. The check can be removed.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/op_set_fk.go
> +	}
I don't think it makes sense to check the length of the column name on the operation here as it must already exist in the database. The check can be removed.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/op_set_notnull.go
> +
I don't think it makes sense to check the length of the column name on the operation here as it must already exist in the database. The check can be removed.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/migrations/op_set_unique.go
> +	}
I don't think it makes sense to check the length of the column name on the operation here as it must already exist in the database. The check can be removed.

2024-03-05 12:07 UTC, andrew-farries commented on pkg/roll/execute.go
> +	}
This is too late to check the length of the new version schema - at this point a potentially lengthy migration start operation has already taken place so it's a poor user experience for the migration to fail with a validation check at this stage. I'd remove the check here and if we need it we can add a check earlier in the migration start process as a separate PR.

2024-04-12 01:42 UTC, andrew-farries commented
Bump @0del 👋 

This PR is almost ready to go; it just needs some removals.

2024-06-19 08:32 UTC, closed without merging