Minor attempt to clear up the behaviour in the documentation
xataio/pgroll pull request #372
Opened 2024-07-17 17:45 UTC by dolezvo1

2024-07-23 07:59 UTC, andrew-farries requested changes
Thanks for adding the extra explanations to the docs 🎉 

I've made some suggested changes to better explain the difference between the versioned schema containing the views and the base schema containing the tables.

2024-07-23 07:59 UTC, andrew-farries commented on docs/README.md
> +After starting a migration there will be two schema versions in the database; one for the old schema before the migration (e.g. `public_02_create_table`) and one for the new version with the schema c
I think it's important to make it clear that the versioned schema (like `public_02_create_table`) contain views on the tables in the `public` schema. Applications using schema managed by`pgroll` shouldn't connect directly to `public` but rather use the versioned views.

```suggestion
After starting a migration there will be two schema versions in the database; one for the old schema before the migration (e.g. `public_02_create_table`) and one for the new version with the schema changes (e.g. `public_03_add_column`).  Each schema contains views on the tables in the `public` schema.
```

2024-07-23 07:59 UTC, andrew-farries commented on docs/README.md
> +Completing a `pgroll` migration removes the previous schema version from the database (e.g. `public_02_create_table`), leaving only the latest version of the schema (e.g. `public_03_add_column`), ava
Another attempt to make it clear that the version schema contain views and the base schema (default `public`) contains the tables.

```suggestion
Completing a `pgroll` migration removes the previous schema version from the database (e.g. `public_02_create_table`), leaving only the latest version of the schema (e.g. `public_03_add_column`). At this point, any temporary columns and triggers created on the affected tables in the `public` schema will also be cleaned up, leaving the table schema in its final state.
```

2024-07-23 15:46 UTC, dolezvo1 commented
@andrew-farries Thank you, for your notes, I actually wasn't even completely aware of this. I will apply your changes and try again.

2024-07-25 13:04 UTC, andrew-farries approved these changes

2024-07-25 13:09 UTC, merged

2024-07-25 14:44 UTC, dolezvo1 commented
Thank you!